name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - run: cargo build --verbose
      - run: cargo test --verbose
